apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: 624480629504.dkr.ecr.us-east-1.amazonaws.com/real_project:patient
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-registry-secret