apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
      - name: appointment
        image: 624480629504.dkr.ecr.us-east-1.amazonaws.com/real_project:appointment
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-registry-secret